"""initial

Revision ID: 165f208648b8
Revises: 
Create Date: 2023-12-25 11:43:23.644878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '165f208648b8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('quantity', sa.Integer(), nullable=False),
        sa.Column('country', sa.String(), nullable=False),  # Змінено тип на String
        sa.Column('customer', sa.Integer(), nullable=False),
        sa.Column('region', sa.DateTime(), nullable=False),
        sa.Column('notes', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['customer'], ['users.id'],  ),
        sa.PrimaryKeyConstraint('id')
    )
    # op.drop_table('addresses')  # Перевірте, чи це дійсно потрібно видалити таблицю
    op.add_column('users', sa.Column('name', sa.String(), nullable=False))
    op.add_column('users', sa.Column('login', sa.String(length=30), nullable=False))
    op.add_column('users', sa.Column('password', sa.String(), nullable=False))
    op.add_column('users', sa.Column('nickname', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('money', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('notes', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_login'), 'users', ['login'], unique=True)
    op.drop_column('users', 'username')
    # op.drop_column('users', 'email')  # Перевірте, чи це дійсно потрібно видалити стовпець
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('users', sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    # op.add_column('users', sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_login'), table_name='users')
    op.drop_column('users', 'notes')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'money')
    op.drop_column('users', 'age')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'nickname')
    op.drop_column('users', 'password')
    op.drop_column('users', 'login')
    op.drop_column('users', 'name')
    op.create_table('addresses',
        sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('country', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column('region', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column('postal_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
        sa.Column('street', sa.VARCHAR(length=100), server_default=sa.text("'вулиця І.Франка'::character varying"), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint('id', name='addresses_pkey')
    )
    op.drop_table('orders')
    # ### end Alembic commands ###
